# =========================================================
# APPLICATION
# =========================================================
spring.application.name=eureka-server
server.port=${PORT:8761}


# =========================================================
# EUREKA SERVER
# =========================================================
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Keep enabled for normal operation
eureka.server.enable-self-preservation=true

# Evict expired instances
eureka.server.eviction-interval-timer-in-ms=60000

# Response cache
eureka.server.response-cache-update-interval-ms=5000


# =========================================================
# SERVER
# =========================================================
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=30s


# =========================================================
# ACTUATOR
# =========================================================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


# =========================================================
# LOGGING
# =========================================================
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO